config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do

  post 'quick_edit_relations', :controller => 'quick_edit_relations', :action => 'create'
  resources :issues do
    shallow do
      resources :quick_edit_relations, :controller => 'quick_edit_relations', :only => [:create, :destroy]
    end
  end

  get 'quick_edit_issues/edit', :controller => 'quick_edit_issues', :action => 'edit'
  get 'quick_edit_issues/replace_preview', :controller => 'quick_edit_issues', :action => 'replace_preview'
  post 'quick_edit_issues/replace', :controller => 'quick_edit_issues', :action => 'replace'
end

app/controllers/quick_edit_issues_controller.rb
class QuickEditIssuesController < ApplicationController
  include ApplicationHelper
  before_action :find_issues
  before_action :check_first_issue
  before_action :check_target_specifier
  before_action :check_replace_args, :only => [:replace, :replace_preview]

  def edit
    custom_field = @dialog_params[:custom_field]
    if custom_field.nil?
      @dialog_params[:description] = nil
    else
      @dialog_params[:description] = custom_field.description.presence if custom_field.attributes().has_key?('description')
    end
    @dialog_params[:description] = nil if (@dialog_params[:description] == "")
    @dialog_params[:issue_ids] = params[:ids]
    @dialog_params[:back_url] = params[:back_url]
    @dialog_params[:default_value] = params[:default_value] unless (params[:default_value].nil?)
  end

  def replace_preview
    @replaced_issues = @issues.map do |issue|
      eval_replace(issue, @attribute_name, @find_regexp, @replace)
    end
  end

  def replace
    emulate_bulk_update = Setting.plugin_quick_edit['emulate_bulk_update']

    Issue.transaction do
      @issues.each do |issue|
        replace_result = eval_replace(issue, @attribute_name, @find_regexp, @replace)
        if replace_result[:before] != replace_result[:after]
          issue.init_journal(User.current, params[:notes])
          issue.safe_attributes = {@attribute_name => replace_result[:after]}
          issue.safe_attributes = {'private_notes' => (params.has_key?(:private_notes) ? '1' : '0')}

          if emulate_bulk_update == 'on'
            emulate_params = { @target_specifier.to_sym => replace_result[after],
                               'ids[]'.to_sym => issue.id,
                               :back_url => params[:back_url] }
            call_hook(:controller_issues_bulk_edit_before_save, { :params => emulate_params, :issue => issue })
          end

          issue.save!
        end
      end
    end

    redirect_to params[:back_url]
  end

private
  # rails filter
  def check_first_issue
    if @issues.empty?
      logger.warn "### quick edit ### issues not found."
      render_404
    end

    @issue = @issues[0]
  end

  # rails filter
  def check_target_specifier
    @target_specifier = params[:target_specifier]
    if @target_specifier.nil?
      logger.warn "### quick edit ### missing target specifier."
      render_error :status => 400
      return
    end

    parsed = parse_target_specifier(@target_specifier)
    if parsed.nil? || parsed.empty?
      logger.warn "### quick edit ### invalid target specifier. target_specifier=" + @target_specifier
      render_error :status => 400
      return
    end

    @attribute_name = parsed[0]
    if parsed.size == 2
      custom_field_id = parsed[1]
      custom_field = @issue.available_custom_fields.detect {|f| f.id.to_s == custom_field_id}
      if custom_field.nil?
        logger.warn "### quick edit ### no available custom field. target_specifier=" + @target_specifier
        head 409, {"X-Quick-Edit-Error" => l(:text_can_not_edit)}
        return false
      end
    end

    unless @attribute_name == :notes
      unless @issue.safe_attribute_names.include?(@attribute_name)
        logger.warn "### quick edit ### no safe attribute. target_specifier=" + @target_specifier
        head 409, {"X-Quick-Edit-Error" => l(:text_can_not_edit)}
        return false
      end
    end

    if custom_field.nil?
      @dialog_params = get_input_dialog_params_for_core_fields(@issue, @target_specifier)
    else
      @dialog_params = get_input_dialog_params_for_custom_fields(@issue, @target_specifier, custom_field)
    end
  end

  # rails filter
  def check_replace_args
    unless @dialog_params[:replacable]
      logger.warn "### quick edit ### no support. target_specifier=" + @target_specifier
      render_error :status => 400
      return
    end

    options = 0
    match_case = params[:match_case].to_s # nil to ""
    unless match_case.empty?
      options = Regexp::IGNORECASE
    end

    @find = params[:find].to_s # nil to ""
    if @find.empty?
      logger.warn "### quick edit ### missing params[find]."
      render_error :status => 400
      return
    end

    if @find.length > 127
      logger.warn "### quick edit ### length over params[find]."
      render_error :status => 400
      return
    end
    @find_regexp = Regexp.new(Regexp.escape(@find), options)

    @replace = params[:replace].to_s # nil to ""
    if @replace.length > 127
      logger.warn "### quick edit ### length over params[replace]."
      render_error :status => 400
      return
    end
    @replace = @replace.gsub(/\\/, '\\\\\\\\')
  end

  def get_input_dialog_params_for_core_fields(issue, target_specifier)
    attribute_name = parse_target_specifier(target_specifier)[0]

    caption = get_attribute_caption(attribute_name)
    field_type = get_attribute_type(attribute_name)
    default_value = issue[attribute_name]
    default_value = "" if default_value.nil?
    validation_pattern = get_field_validation_pattern(field_type)
    help_message = get_field_help_message(field_type)
    clear_pseudo_value = nil
    clear_pseudo_value = 'none' if %w(parent_issue_id start_date due_date estimated_hours).include?(attribute_name)
    replacable = %w(subject).include?(attribute_name)

    ret =
      { :attribute_name => attribute_name.to_sym,
        :caption => caption,
        :target_specifier => target_specifier,
        :field_type => field_type,
        :default_value => default_value,
        :validation_pattern => validation_pattern,
        :help_message => help_message,
        :clear_pseudo_value => clear_pseudo_value,
        :replacable => replacable,
        :custom_field => nil
      }
  end

  def get_input_dialog_params_for_custom_fields(issue, target_specifier, custom_field)
    attribute_name = parse_target_specifier(target_specifier)[0]

    caption = custom_field.name
    field_type = custom_field.field_format.to_sym
    default_value = issue.editable_custom_field_values.detect {|v| v.custom_field_id == custom_field.id}
    default_value = "" if default_value.nil?
    validation_pattern = get_field_validation_pattern(field_type)
    help_message = get_field_help_message(field_type)
    replacable = false

    ret =
      { :attribute_name => attribute_name.to_sym,
        :caption => caption,
        :target_specifier => target_specifier,
        :field_type => field_type,
        :default_value => default_value,
        :validation_pattern => validation_pattern,
        :help_message => help_message,
        :clear_pseudo_value => '__none__',
        :replacable => replacable,
        :custom_field => custom_field
      }
  end

  def get_field_validation_pattern(field_type)
     case field_type.to_sym
     when :string
        pattern = ''
     when :text
        pattern = ''
     when :int
        pattern = '\d+'
     when :float
        pattern = '^[+-]?(\d+|\d*\.\d+|\d+\.\d+)($|[eE][+-]?\d+$)'
     when :date
        pattern = '\d{4}-\d{2}-\d{2}'
     end
  end

  def get_field_help_message(field_type)
    help_message= l(:text_edit_confirm)
    help_message += " (yyyy-mm-dd)" if field_type == :date
    help_message
  end

  def eval_replace(issue, attribute_name, find_regexp, replace)
      before = issue[attribute_name].to_s # nil to ""
      after = before.gsub(find_regexp, replace)

      { :id  => issue.id,
        :before => before,
        :after =>  after}
  end
end

app/views/quick_edit_issues/_input_dialog.html.erb
<%
  dialog_size = parse_size(Setting.plugin_quick_edit['input_dialog_base_size'], 480...2048, 500, 280...2048, 280)
  dialog_size[0] += 227 if @dialog_params[:field_type] == :text || @dialog_params[:field_type] == :string || @dialog_params[:field_type] == :link
  dialog_size[1] += 130 if @dialog_params[:field_type] == :text
  dialog_size[1] += 185 # for notes
  dialog_size[1] += 25 if @dialog_params[:attribute_name]==:description
  dialog_size[1] -= 160 if @dialog_params[:attribute_name].to_sym == :notes
  dialog_size[1] += 50 unless @dialog_params[:description].nil?

  textarea_size = parse_size(Setting.plugin_quick_edit['textarea_size'], 10...256, 80, 10...256, 10)
%>
<div id="quick_edit_input_dialog" title="Quick Edit - <%= @dialog_params[:caption] %>">
  <!-- main begin -->
  <div>
    <div class="header">
      <span class="message"><%= @dialog_params[:help_message] %></span><br>
      <span class="ids">for: <% @issues.each do |issue| %><%= link_to("\##{issue.id}", issue_path(issue), :class => :issue) %>&nbsp;<% end %></span>
    </div>

    <!-- page switcher -->
    <% if @dialog_params[:replacable] %>
    <div class="page-switchers">
      <ul>
        <li id="edit_switcher" class="page-switcher" style="display:none;"><a>&lt;&lt; EDIT</a></li>
        <li id="replace_switcher" class="page-switcher"><a>REPLACE &gt;&gt;</a></li>
      </ul>
    </div>
    <% end %>

    <!-- pages  -->
    <div id="edit-page" class="page">

      <%= form_tag({:controller=>'issues', :action=>:bulk_update}) do %>
      <div class="box" style="overflow: auto">
        <% if @dialog_params[:attribute_name].to_sym == :notes %>
          <span><%= @dialog_params[:caption] %>(Add only):</span>
          <textarea id="new_value"
                    name="new_value"
                    class="full_width"
                    rows="5"
                    style="vertical-align:middle"></textarea>
          <%= wikitoolbar_for :new_value %>
          <input id="issue_private_notes"
                 name="issue[private_notes]"
                 type="checkbox"
                 value="1"/>
          <label for="issue_private_notes"><%= l(:field_private_notes) %></label>
        <% else %>
          <span><%= @dialog_params[:caption] %>:</span>
          <% case @dialog_params[:field_type] %>
          <% when :date %>
          <input id="new_value"
                 type="text" 
                 size="15"
                 value="<%= @dialog_params[:default_value] %>"></input>
          <%= calendar_for('new_value') %>
          <% when :int, :float %>
          <input id="new_value"
                 type="text" 
                 size="15"
                 value="<%= @dialog_params[:default_value] %>"></input>
            <% if @dialog_params[:target_specifier] == "issue[parent_issue_id]" %>
            <%= javascript_tag "observeAutocompleteField('new_value', '#{escape_javascript auto_complete_issues_path(:project_id => @issue.project, :scope => (Setting.cross_project_issue_relations? ? 'all' : nil))}')" %>
            <%= javascript_tag "setPredecessorFieldsVisibility();" %>
            <% end %>
          <% when :text %>
          <textarea id="new_value"
                 class="full_width"
                 cols="<%= textarea_size[0] %>"
                 rows="<%= textarea_size[1] %>"
                 style="vertical-align:middle;"><%= @dialog_params[:default_value] %></textarea>
          <% if @dialog_params[:attribute_name].to_sym == :description %>
          <%= wikitoolbar_for 'new_value' %>
          <% end %>
          <% else %>
          <input id="new_value"
                 type="text"
                 class="full_width"
                 size="80"
                 value="<%= @dialog_params[:default_value] %>"></input>
               <% end %>
          <% unless @dialog_params[:clear_pseudo_value].nil? %>
            <input id="clear" name="clear" type="checkbox" value="<%= @dialog_params[:clear_pseudo_value] %>" data-disables="#new_value"><%= l(:button_clear) %></input>
          <% end %>

          <% if !@dialog_params[:description].nil? %>
          <pre style="border: 1px solid #e0e0e0; padding: 3px; overflow:auto; height: 2.8em; margin-top: 10px; margin-bottom: 0px;"><%= @dialog_params[:description] %></pre>
          <% end %>

          <fieldset style="margin-top: 10px;">
            <legend><%= l(:field_notes) %></legend>
            <textarea id="notes_for_edit"
                      name="notes"
                      class="full_width"
                      rows="5"
                      style="vertical-align:middle"></textarea>
            <%= wikitoolbar_for :notes_for_edit %>
            <input id="issue_private_notes_for_edit"
                   name="issue[private_notes]"
                   type="checkbox"
                   value="1"/>
            <label for="issue_private_notes_for_edit"><%= l(:field_private_notes) %></label>
          </fieldset>
        <% end %>
        <% @dialog_params[:issue_ids].each do |id| %>
        <input id="ids" name="ids[]" type="hidden" value="<%= id %>"></input>
        <% end %>
        <input id="target_specifier" name="target_specifier" type="hidden" value="<%= @dialog_params[:target_specifier] %>"></input>
        <input id="back_url" name="back_url" type="hidden" value="<%= @dialog_params[:back_url] %>"></input>
        <input id="validation_pattern" type="hidden" value="<%= @dialog_params[:validation_pattern] %>"></input>
      </div>
      <% end %>
    </div>

    <div id="replace-page" class="page" style="display: none;">
      <%= form_tag({:controller=>'quick_edit_issues', :action=>:replace}) do %>
      <div class="box">
        <span><%= l(:label_find_with) %>:</span><br/>
        <input id="find"
               name="find"
               type="text"
               class="full_width"
               size="80"
               value="<%= @dialog_params[:default_value] %>"></input><br/>
        <span><%= l(:label_replace_with) %>:</span><br/>
        <input id="replace"
               name="replace"
               type="text"
               class="full_width"
               size="80"
               value=""></input><br/>
        <div class="options">
          <input id="match_case"
                 name="match_case"
                 type="checkbox"
                 value="true"></input>
          <span><%= l(:label_match_case) %></span>
        </div>
        <span><%= l(:label_preview) %>:</span>
        <div id="preview_area" class="ui-corner-all box">&nbsp;</div>

        <fieldset style="margin-top: 10px;">
          <legend><%= l(:field_notes) %></legend>
          <textarea id="notes_for_replace"
                    name="notes"
                    class="full_width"
                    rows="5"
                    style="vertical-align:middle"></textarea>
          <%= wikitoolbar_for :notes_for_replace %>
          <input id="issue_private_notes_for_replace"
                 name="private_notes"
                 type="checkbox"
                 value="1"/>
          <label for="issue_private_notes_for_replace"><%= l(:field_private_notes) %></label>
        </fieldset>
      </div>
      <input id="target_specifier" name="target_specifier" type="hidden" value="<%= @dialog_params[:target_specifier] %>"></input>
      <input id="back_url" name="back_url" type="hidden" value="<%= @dialog_params[:back_url] %>"></input>
      <% @dialog_params[:issue_ids].each do |id| %>
      <input id="ids" name="ids[]" type="hidden" value="<%= id %>"></input>
      <% end %>
      <% end %>
    </div>

  </div>
  <!-- main end -->

  <!-- footer -->
  <div class="footer">
    <span>QUICK EDIT</span><br>
    <span style="font-size: 9px;">http://osdn.jp/projects/quickedit/</span>
  </div>
</div>

<script>
//<![CDATA[
  $("#clear").bind("click", function () {
    var target=$($(this).data("disables"));
    target.prop("disabled", !target.prop("disabled"));
  });
  $(".ui-autocomplete").css("z-index",200);
  $(".page-switcher").click( quick_edit_input_dialog_switch_page );
  $("#quick_edit_input_dialog").dialog({
     modal: true,
     closeOnEscape: false,
     width: <%= dialog_size[0] %>,
     height: <%= dialog_size[1] %>,
     buttons: {
        "Submit" : quick_edit_input_dialog_edit_submit,
        "Cancel" : quick_edit_input_dialog_cancel
     },
     open: quick_edit_input_dialog_open,
     close: quick_edit_input_dialog_close
  });
  $("#quick_edit_input_dialog").click( function(e) { e.stopPropagation(); } );
  $("#quick_edit_input_dialog #edit-page #new_value").focus();
  quick_edit_log("input_dialog open. size=<%=dialog_size[0]%>,<%=dialog_size[1]%>");
//]]>
</script>

app/views/quick_edit_issues/_replace_preview.html.erb
<table class="list issues">
<thead>
<tr>
  <th class="id">#</th><th class="before">Before</th><th class="after">After</th>
</tr>
</thead>
<tbody>
<% @replaced_issues.each do |issue| %>
<% cycle_class = cycle(:odd, :even) %>
<tr class="issue">
  <td class="id <%= cycle_class %>"><%= issue[:id] %></td><td class="before <%= cycle_class %>"><%= issue[:before] %></td><td class="after <%= cycle_class %>"><%= issue[:after] %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/quick_edit_issues/_settings.html.erb
<table>
	<tr>
		<th>Dialog base size:</th>
    <td>
    <input type="text" id="settings_input_dialog_base_size" name="settings[input_dialog_base_size]" value="<%= settings['input_dialog_base_size'] %>"></input>
    </td>
    <td>
    </td>
	</tr>
	<tr>
		<th>Textarea size:</th>
    <td>
    <input type="text" id="settings_textarea_size" name="settings[textarea_size]" value="<%= settings['textarea_size'] %>"></input>
    </td>
    <td>
    </td>
	</tr>
	<tr>
		<th>Pattern of name for exclude custom fields:</th>
    <td>
    <input type="text" id="settings_custom_field_exclude_names" name="settings[custom_field_exclude_names]" value="<%= settings['custom_field_exclude_names'] %>"></input>
    </td>
    <td>
    </td>
	</tr>
  <tr>
    <th>Emulate bulk update </th>
    <td>
      <input type="checkbox" id="settings_emulate_bulk_update" name="settings[emulate_bulk_update]" value="on" <%= settings['emulate_bulk_update'] == 'on' ? 'checked' : '' %>></input>
    </td>
    <td>If you check, replace function calls the hook of "controller_issues_bulk_edit_before_save".</td>
</table>

app/views/quick_edit_issues/edit.js.erb
$("#quick_edit_input_dialogs").html(
  "<%= escape_javascript(render :partial => 'input_dialog', :layout => false ) %>"
);

app/views/quick_edit_issues/replace_preview.js.erb
$("#preview_area").html(
  "<%= escape_javascript(render :partial => 'replace_preview', :layout => false ) %>"
);