config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do

  post 'quick_edit_relations', :controller => 'quick_edit_relations', :action => 'create'
  resources :issues do
    shallow do
      resources :quick_edit_relations, :controller => 'quick_edit_relations', :only => [:create, :destroy]
    end
  end

  get 'quick_edit_issues/edit', :controller => 'quick_edit_issues', :action => 'edit'
  get 'quick_edit_issues/replace_preview', :controller => 'quick_edit_issues', :action => 'replace_preview'
  post 'quick_edit_issues/replace', :controller => 'quick_edit_issues', :action => 'replace'
end

app/views/hooks/_quick_edit_base_bottom.html.erb
<div id="quick_edit">
  <div id="quick_edit_input_dialogs"></div>
  <div id="quick_edit_flash" class="flash error" 
    style="display: none; z-index: 1000; position: fixed; top: 10px; left: 10px; opacity: 0.9; min-width: 300px; background-color: #ffe3e3;">
    <div style="padding: 10px 5px;"> 
      <span id="quick_edit_flash_message"></span>
    </div> 
  </div>
</div>
<script>
//<![CDATA[
function quick_edit_log(message){
  if(typeof console !== "undefined" && typeof console.log !=="undefined")
    console.log("quick_edit: "+message);
}

function quick_edit_setup_ajax_error_handler() {
  $(document).ajaxError( function (event, jqXHR, ajaxSettings, thrownError) {
    if (! (/quick_edit/.test(ajaxSettings.url))) return;

    var message =  jqXHR.status + " " + (jqXHR.getResponseHeader("X-Quick-Edit-Error") || thrownError || jqXHR.statusText);
    $("#quick_edit_flash_message").text(message);

    var flash = $("#quick_edit_flash");
    flash.click( function(e) { e.stopPropagation(); } );
    flash.fadeIn(500, function () {
      setTimeout( function() { flash.fadeOut(); }, 3000)
    });
  });
}

var offsetY = /[?&]offsetY=(\d+).*/g.exec(location.href);
if (offsetY) {
  window.scrollTo(0, offsetY[1]);
}

quick_edit_setup_ajax_error_handler();
quick_edit_drag_and_drop_init();

function quick_edit_drag_and_drop_init() {
  if ($("body").hasClass("controller-issues action-index")) {
    $("tr.issue").draggable({
      axis: "y",
      cursor: "move",
      containment: "parent",
      scope: "issue",
      snap: true,
      opacity: 0.5,
      helper: function () { return $('<div></div>'); },
      start: function (event, ui) {
        drag_element = $(this);
        if (!drag_element.hasClass("context-menu-selection")) {
          drag_element.addClass("context-menu-selection");
        }
    
        ui.helper.css( {
          "width": drag_element.css("width"),
          "height": drag_element.css("height"),
          "background-color": drag_element.css("background-color")});
      }
    });
  
    $("tr.issue").droppable({
      scope: "issue",
      drop: function (event, ui) {
        var update_ids = quick_edit_get_selections();
        var new_parent_id = quick_edit_get_issue_id_from_element(this);
        if (!new_parent_id) return;

        $.ajax({
          url: '<%= quick_edit_issues_edit_path() %>?' + update_ids.join("&") + '&target_specifier=issue[parent_issue_id]&default_value='+new_parent_id,
          dataType: "script",
          success : function (html) { $("#quick_edit_dialogs").html(html); }
        });
      }
    });
  }
}

function quick_edit_drag_and_drop_enable(){
  $("tr.issue.ui-draggable").each( function () {
    var issue = $(this);
    issue.draggable("enable");
  });
  $("tr.issue.ui-droppable").each( function () {
    var issue = $(this);
    issue.droppable("enable");
  });

  quick_edit_log("issue d&d enabled.");
}

function quick_edit_drag_and_drop_disable(){
  $("tr.issue.ui-draggable").each( function () {
    var issue = $(this);
    issue.draggable("disable");
  });
  $("tr.issue.ui-droppable").each( function () {
    var issue = $(this);
    issue.droppable("disable");
  });
  
  quick_edit_log("issue d&d disabled.");
}

function quick_edit_get_selections() {
    var ids = [];
    $(".context-menu-selection").each(function (index,element) {
      var id = quick_edit_get_issue_id_from_element(element);
      ids.push("ids[]="+id);
    });
    return ids;
}

function quick_edit_get_issue_id_from_element(element) {
  var id = $(element).attr("id");
  var m = /issue-(.*)/.exec(id);
  return m[1];
}

function quick_edit_input_dialog_switch_page() {
  var dialog = $("#quick_edit_input_dialog");

  var switchers = dialog.find(".page-switcher");
  switchers.toggle();

  var pages = dialog.find(".page");
  pages.toggle();

  if (dialog.find("#replace_switcher:hidden").length == 1) {
    dialog.find("#find").focus();
    dialog.dialog("option", "buttons",
      [ { text: "Preview", click: quick_edit_input_dialog_preview_replace},
        { text: "Submit", click: quick_edit_input_dialog_replace_submit},
        { text: "Cancel", click: quick_edit_input_dialog_cancel}]);

  } else {
    dialog.find("#new_value").focus();
    dialog.dialog("option", "buttons",
      [ { text: "Submit", click: quick_edit_input_dialog_edit_submit},
        { text: "Cancel", click: quick_edit_input_dialog_cancel}]);
  }
}

function quick_edit_input_dialog_preview_replace() {
  var replace_page = $("#quick_edit_input_dialog #replace-page");

  var target_specifier = replace_page.find("#target_specifier").val();
  var find = replace_page.find("#find").val();
  var replace = replace_page.find("#replace").val();
  var match_case = replace_page.find("#match_case:checked").val();
  var ids = [];
  replace_page.find("#ids").each( function () { ids.push($(this).val()); });
  var url="<%= quick_edit_issues_replace_preview_path() %>";

  if(find == "") {
    alert('<%=l(:text_is_required)%>');
    return;
  }

  $.ajax({
     url: url,
     data: {ids: ids, target_specifier: target_specifier, find: find, replace: replace, match_case: match_case},
     dataType: 'script'});
}

function quick_edit_input_dialog_replace_submit() {
  var replace_page = $("#quick_edit_input_dialog #replace-page");

  var find = replace_page.find("#find").val();
  if(find == "") {
    alert('<%=l(:text_is_required)%>');
    return;
  }

  if (!confirm('<%= l(:text_are_you_sure) %>')) {
    return;
  }

  replace_page.find("form").submit();
}

function quick_edit_input_dialog_open(){
  quick_edit_drag_and_drop_disable();
}

function quick_edit_input_dialog_close(){
  quick_edit_drag_and_drop_enable();
  $("#quick_edit_input_dialog").remove();
}

function quick_edit_input_dialog_cancel(){
  $("#quick_edit_input_dialog").dialog("close");
}

function quick_edit_clear(){
}

function quick_edit_input_dialog_edit_submit(){
  var edit_page = $("#quick_edit_input_dialog #edit-page");

  var target_specifier = edit_page.find("#target_specifier").val();
  var new_value_element = edit_page.find("#new_value");
  var clr_value_element = edit_page.find("#clear");

  if (edit_page.find("#clear:checked").length > 0){
    new_value_element.attr("name", "_quick_edit_tmp");
    clr_value_element.attr("name", target_specifier);

  } else {
    new_value_element.attr("name", target_specifier);
    clr_value_element.attr("name", "_quick_edit_tmp");

    var new_value = edit_page.find("#new_value").val();
    if(new_value === null) return;

    var pattern = new RegExp(edit_page.find("#validation_pattern").val());

    if(new_value == "") {
      alert('<%=l(:text_is_required)%>');
      return;

    } else {

      if(pattern && !pattern.test(new_value)){
         alert('<%=l(:text_invalid_format)%>');
         return;
      }
    }
  }

  var issue_ids = [];
  edit_page.find("#ids").each(function (index,element) {
    issue_ids.push($(this).val());
  });
  if(issue_ids.length>1){
     if(!confirm('<%=l(:text_multiple_update_confirm)%>')) return;
  }

  var offsetY = (window.pageYOffset !== undefined) ? window.pageYOffset : (document.documentElement || document.body.parentNode || document.body).scrollTop;
  var back_url = edit_page.find("#back_url").val();
  if (back_url.indexOf("?") == -1) {
    back_url = back_url + "?offsetY=" + offsetY;
  } else {
    back_url = back_url + "&offsetY=" + offsetY;
  }
  edit_page.find("#back_url").val(back_url);

  edit_page.find("form").submit();
}

function quick_edit_show_new_relation_dialog(first_issue_id, second_issue_id, back_url){
  $("#quick_edit_new_relation_dialog > form > #issue_id").val(first_issue_id);
  $("#quick_edit_new_relation_dialog > form > #relation_issue_to_id").val(second_issue_id);
  $("#quick_edit_new_relation_dialog > form > #back_url").val(back_url);
  $("#quick_edit_new_relation_dialog").dialog({
     modal: true,
     closeOnEscape: false,
     width: 450,
     height: 150,
     open: quick_edit_new_relation_dialog_open,
     close: quick_edit_new_relation_dialog_close
  });

  quick_edit_log("new_relation dialog open.");
}

function quick_edit_new_relation_dialog_cancel(){
   $('#quick_edit_new_relation_dialog').dialog("close");
}

function quick_edit_new_relation_dialog_open(){
  quick_edit_drag_and_drop_disable();
}

function quick_edit_new_relation_dialog_close(){
  quick_edit_drag_and_drop_enable();
}

//]]>
</script>

app/views/hooks/_quick_edit_base_head.html.erb
<% include_calendar_headers_tags %>
<% heads_for_wiki_formatter %>
<style>
#quick_edit_input_dialog {
  background-color: white;
}

#quick_edit_input_dialog .page-switchers {
  padding: 5px;
  margin: 0px;
  text-align: right;
}

#quick_edit_input_dialog .page-switchers ul {
  padding: 0px;
  margin: 0px;
}

#quick_edit_input_dialog .page-switcher {
  list-style: none;
  font-size: 0.8em;
}

#quick_edit_input_dialog .page-switcher a, #quick_edit_input_dialog .page-switcher a:visited {
  color: #169;
}

#quick_edit_input_dialog .page-switcher a:hover {
  color: #C61A1A;
}

#quick_edit_input_dialog .header {
  overflow: hidden;
  padding-top: 9px;
  padding-bottom: 9px;
  padding-left: 10px;
}

#quick_edit_input_dialog .header .message {
  vertical-align: middle;
  font-size: 1em;
}

#quick_edit_input_dialog .header .ids {
  vertical-align: middle;
  font-size: 0.85em;
}

#quick_edit_input_dialog .box {
  font-size: 0.9em;
  font-weight: normal;
  padding-left: 10px;
  padding-right: 10px;
  padding-bottom: 12px;
  margin-bottom: 0px;
}

#quick_edit_input_dialog .options {
  padding-top: 7px;
  padding-bottom: 7px;
}

#quick_edit_input_dialog .full_width {
  width: 98.8%;
}

#quick_edit_input_dialog #preview_area {
  padding-bottom: 6px;
}

#quick_edit_input_dialog #preview_area table {
  margin-bottom: 0px;
}

#quick_edit_input_dialog #preview_area .id {
  text-align: middle;
}

#quick_edit_input_dialog #preview_area .before, #quick_edit_input_dialog #preview_area .after {
  text-align: left;
  width: 45%;
  white-space: pre-wrap;
  word-wrap: break-word;
  word-break: break-all;
}

#quick_edit_input_dialog .footer {
  color: #a0a0a0;
  text-align: right;
  margin-top: 3px;
  padding-top: 12px;
  line-height: 1.0em;
}

</style>

app/views/hooks/_quick_edit_context.html.erb
<%
   extend ApplicationHelper
   extend IssueRelationsHelper

   excludes = Setting.plugin_quick_edit['custom_field_exclude_names'].split(/,/).map {|v| Regexp.new(v)}

   custom_fields = @issues.map(&:available_custom_fields).reduce(:&).select do |f|
     %w{string date int text link float}.include?(f.field_format) && ( excludes.empty? || excludes.none? {|ex| ex.match(f.name)} )
   end

   readonly_fields = @issues.map {|issue| issue.read_only_attribute_names(User.current)}
   readonly_fields.flatten!
   readonly_fields.uniq!

   first_issue = @issues.first
   first_issue_id = first_issue.id
   if @issues.size > 1
      second_issue = @issues[1]
      second_issue_id = second_issue.id
   else
      second_issue_id = ''
   end

   # 可能なら更新後に選択されたチケットに戻り先に設定
   if @back.match(/\/projects\/.*?\/issues/)
     back_url = @back + '#issue-' + first_issue.id.to_s
   else
     back_url = @back
   end

%>
  <li class="folder">
    <a id="quick_edit_context" href="#" class="submenu"><%= l(:button_quick_edit) %></a>
    <ul>
      <%= quick_edit_link_to(@issue_ids, get_attribute_caption(:subject), :subject, nil, back_url, !editable(:subject,@can,readonly_fields)) %>
      <%= quick_edit_link_to(@issue_ids, get_attribute_caption(:description), :description, nil, back_url, !editable(:description,@can,readonly_fields)) %>
      <%= quick_edit_link_to(@issue_ids, get_attribute_caption(:parent_issue_id), :parent_issue_id, nil, back_url, !editable(:parent_issue_id,@can,readonly_fields)) %>
      <% unless @issues.any? {|issue| issue.disabled_core_fields.include?('start_date') } %>
      <%= quick_edit_link_to(@issue_ids, get_attribute_caption(:start_date), :start_date, nil, back_url, !editable(:start_date,@can,readonly_fields)) %>
      <% end %>

      <% unless @issues.any? {|issue| issue.disabled_core_fields.include?('due_date') } %>
      <%= quick_edit_link_to(@issue_ids, get_attribute_caption(:due_date), :due_date, nil, back_url, !editable(:due_date,@can,readonly_fields)) %>
      <% end %>

      <% unless @issues.any? {|issue| issue.disabled_core_fields.include?('estimated_hours') } %>
      <%= quick_edit_link_to(@issue_ids, get_attribute_caption(:estimated_hours), :estimated_hours, nil, back_url, !editable(:estimated_hours,@can,readonly_fields)) %>
      <% end %>

      <% custom_fields.each do |f| %>
      <%= quick_edit_link_to(@issue_ids, f.name, 'custom_field_values', f.id, back_url, !editable_custom_field(f,@can,readonly_fields)) %>
      <% end %>

      <%= quick_edit_link_to(@issue_ids, get_attribute_caption(:notes), :notes, nil, back_url, !editable(:notes,@can,readonly_fields), %s{icon-comment}) %>

      <% if @issues.size <= 2  %>
        <% if User.current.allowed_to?(:manage_issue_relations, @project) %>
        <hr>
        <li><%= link_to l(:label_relation_new),
                        'javascript: quick_edit_show_new_relation_dialog(\''+first_issue_id.to_s+'\',\''+second_issue_id.to_s+'\',\''+URI.encode_www_form_component(back_url)+'\');',
                        :remote => false,
                        :title => l(:label_relation_new),
                        :class => 'icon',
                        :style => 'background-image: url("'+image_path('link.png')+'")' %></li>
        <% end %>
      <% end %>

      <% if @issues.size == 1 && first_issue.relations.any? %>
        <hr>
        <% first_issue.relations.each do |relation| %>
          <% other_issue = relation.other_issue(first_issue) %>
          <% if User.current.allowed_to?(:manage_issue_relations, @project) %>
            <li><%= link_to l(relation.label_for(first_issue)) + " \##{other_issue.id}",
                            quick_edit_relation_path(relation, :back_url => back_url),
                            :remote => false,
                            :method => :delete,
                            :data => {:confirm => l(:text_are_you_sure)},
                            :title => l(:label_relation_delete),
                            :class => 'icon',
                            :style => 'background-image: url("'+image_path('link_break.png')+'");' %></li>
          <% end %> 
        <% end %>
      <% end %>
   </ul>
  </li>

  <div id="quick_edit_new_relation_dialog" style="display:none;" title="Quick Edit - <%= l(:label_relation_new) %>">
    <%= form_tag({:controller=>'quick_edit_relations', :action=>:create}) do %>
      <%= text_field_tag :issue_id, '', { :size => 10 } %>
      <%= select :relation, :relation_type, collection_for_relation_type_select, {}, :onchange => "setPredecessorFieldsVisibility();"  %>
      <%= text_field_tag 'relation[issue_to_id]', '', { :size => 10 } %>
      <%= hidden_field_tag :back_url, '' %>
      <span id="predecessor_fields" style="display:none;">
      <br><%= l(:field_delay) %>: <%= text_field_tag :delay, '', {:size => 3} %> <%= l(:label_day_plural) %>
      </span><br>
      <hr> 
      <%= submit_tag l(:button_add) %>
      <%= submit_tag l(:button_cancel), :onclick => 'javascript: quick_edit_new_relation_dialog_cancel();', :type => 'button' %>

      <%= javascript_tag "observeAutocompleteField('issue_id', '#{escape_javascript auto_complete_issues_path(:project_id => @project, :scope => (Setting.cross_project_issue_relations? ? 'all' : nil))}')" %>
      <%= javascript_tag "observeAutocompleteField('relation_issue_to_id', '#{escape_javascript auto_complete_issues_path(:project_id => @project, :scope => (Setting.cross_project_issue_relations? ? 'all' : nil))}')" %>

      <%= javascript_tag "setPredecessorFieldsVisibility();" %>

    <% end %>
  </div>